# -*- coding: utf-8 -*-
"""
/***************************************************************************
 GuideInteractifHtml
                                 A QGIS plugin
 guide interactif pour les utilisateurs ONF
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2026-03-11
        copyright            : (C) 2026 by Robin FICHT
        email                : robin.ficht@onf.fr
        git sha              : $Format:%H$
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""


# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load GuideInteractifHtml class from file GuideInteractifHtml.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    from .guide_interactif_html import GuideInteractifHtml
    return GuideInteractifHtml(iface)
