# -*- coding: utf-8 -*-
"""
/***************************************************************************
 GuideInteractifHtml
                                 A QGIS plugin
 guide interactif pour les utilisateurs ONF
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                              -------------------
        begin                : 2026-03-11
        git sha              : $Format:%H$
        copyright            : (C) 2026 by Robin FICHT
        email                : robin.ficht@onf.fr
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
"""
import os.path

from qgis.PyQt.QtCore import QCoreApplication, QSettings, Qt, QTranslator
from qgis.PyQt.QtGui import QIcon
from qgis.PyQt.QtWidgets import QAction

from .guide_launcher import GuideLauncherDockWidget
from .resources import *


class GuideInteractifHtml:
    """QGIS Plugin Implementation."""

    def __init__(self, iface):
        """Constructor.

        :param iface: An interface instance that will be passed to this class
            which provides the hook by which you can manipulate the QGIS
            application at run time.
        :type iface: QgsInterface
        """
        self.iface = iface
        self.plugin_dir = os.path.dirname(__file__)
        locale = QSettings().value('locale/userLocale')[0:2]
        locale_path = os.path.join(
            self.plugin_dir,
            'i18n',
            'GuideInteractifHtml_{}.qm'.format(locale))

        if os.path.exists(locale_path):
            self.translator = QTranslator()
            self.translator.load(locale_path)
            QCoreApplication.installTranslator(self.translator)

        self.actions = []
        self.menu = self.tr(u'&GuideInteractifHtml')
        self.dock_widget = None
        self.first_start = None

    def tr(self, message):
        """Get the translation for a string using Qt translation API."""
        return QCoreApplication.translate('GuideInteractifHtml', message)

    def add_action(
        self,
        icon_path,
        text,
        callback,
        enabled_flag=True,
        add_to_menu=True,
        add_to_toolbar=True,
        status_tip=None,
        whats_this=None,
        parent=None):
        """Add a toolbar icon to the toolbar."""

        icon = QIcon(icon_path)
        action = QAction(icon, text, parent)
        action.triggered.connect(callback)
        action.setEnabled(enabled_flag)

        if status_tip is not None:
            action.setStatusTip(status_tip)

        if whats_this is not None:
            action.setWhatsThis(whats_this)

        if add_to_toolbar:
            self.iface.addToolBarIcon(action)

        if add_to_menu:
            self.iface.addPluginToMenu(self.menu, action)

        self.actions.append(action)
        return action

    def initGui(self):
        """Create the menu entries and toolbar icons inside the QGIS GUI."""

        icon_path = ':/plugins/guide_interactif_html/icon.png'
        self.add_action(
            icon_path,
            text=self.tr(u'Ouvrir le lanceur de guides'),
            callback=self.run,
            parent=self.iface.mainWindow())

        self.first_start = True

    def unload(self):
        """Removes the plugin menu item and icon from QGIS GUI."""
        if self.dock_widget is not None and hasattr(self.iface, 'removeDockWidget'):
            self.iface.removeDockWidget(self.dock_widget)
            self.dock_widget = None

        for action in self.actions:
            self.iface.removePluginMenu(self.tr(u'&GuideInteractifHtml'), action)
            self.iface.removeToolBarIcon(action)

    def _create_dock_widget(self):
        self.dock_widget = GuideLauncherDockWidget(
            self.plugin_dir,
            self.iface.mainWindow(),
        )
        self.iface.addDockWidget(Qt.RightDockWidgetArea, self.dock_widget)

    def run(self):
        """Open or focus the dock widget used to launch HTML guides."""
        if self.first_start is True or self.dock_widget is None:
            self.first_start = False
            self._create_dock_widget()

        self.dock_widget.show()
        self.dock_widget.raise_()